config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'landingpage#index'
  get 'landingpage/index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landingpage_controller.rb
class LandingpageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landingpage/index.html.haml
= render 'shared/teaser_header'
= render 'shared/testimonials'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.haml
- if user_signed_in?
  %li= link_to 'Account', edit_user_registration_path
  %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  %li= link_to 'Sign in', new_user_session_path
  %li= link_to 'Sign up', new_user_registration_path

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
        = render 'layouts/nav_links_for_auth'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "FOSS.buzz"
      %meta{:content => content_for?(:description) ? yield(:description) : "FOSS.buzz", :name => "description"}
        = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
        = javascript_include_tag 'application', 'data-turbolinks-track' => true
        = csrf_meta_tags
  %body.layout
    %header
      = render 'layouts/navigation'
    %main.layout__contentArea{:role => "main"}
      = render 'layouts/messages'
      = yield
      = render 'shared/footer'

app/views/shared/_account.html.haml
.account
  .authform.formBlock
    = form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put, :role => 'form'}) do |f|
      = devise_error_messages!
      .form-group
        = f.label :email
        = f.email_field :email, :autofocus => true, class: 'form-control'
        - if devise_mapping.confirmable? && resource.pending_reconfirmation?
          %div
            Currently waiting confirmation for: #{resource.unconfirmed_email}
      %fieldset
        %p Leave these fields blank if you don't want to change your password.
        .form-group
          = f.label :password
          = f.password_field :password, :autocomplete => 'off', class: 'form-control'
        .form-group
          = f.label :password_confirmation
          = f.password_field :password_confirmation, class: 'form-control'
      %fieldset
        %p You must enter your current password to make changes.
        .form-group
          = f.label :current_password
          = f.password_field :current_password, class: 'form-control'
      = f.submit 'Update', :class => 'btn btn-primary'
  .authform.formBlock
    = button_to "Delete account", registration_path(resource_name), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-danger'

app/views/shared/_footer.html.haml
.footer.container
  .row
    .footer__column.col-md-12.col-lg-4
      .footer__card
        %h4
          Shortcuts
        %ul
          %li
            %a{:href => 'https://gitlab.com/jacob-dawid/foss.buzz', :target => '_blank'}
              Log in
          %li
            %a{:href => 'http://www.gnu.org/licenses/', :target => '_blank'}
              Sign up
          %li
            %a{:href => 'http://www.gnu.org/licenses/', :target => '_blank'}
              View all projects

    .footer__column.col-md-12.col-lg-4
      .footer__card
        %h4
          Help us develop
        %ul
          %li
            %a{:href => 'https://gitlab.com/jacob-dawid/foss.buzz', :target => '_blank'}
              FOSS.buzz source code

    .footer__column.col-md-12.col-lg-4
      .footer__card
        %h4
          Further Links
        %ul
          %li
            %a{:href => 'http://www.gnu.org/licenses/', :target => '_blank'}
              Free software licenses
  .row
    .footer__column
      Copyright 2016 FOSS.buzz Developers

app/views/shared/_password_change.html.haml
.passwordChange
  .authform.formBlock
    = form_for(resource, :as => resource_name, :url => password_path(resource_name), :html => { :method => :put }) do |f|
      = devise_error_messages!
      = f.hidden_field :reset_password_token
      .form-group
        = f.label :password, 'New password'
        = f.password_field :password, autofocus: true, autocomplete: 'off', class: 'form-control'
        = f.label :password_confirmation, 'Confirm new password'
        = f.password_field :password_confirmation, autocomplete: 'off', class: 'form-control'
      = f.submit 'Change my Password', :class => 'btn btn-primary'

app/views/shared/_password_restore.html.haml
.passwordRestore
  .authform.formBlock
    = form_for(resource, :as => resource_name, :url => password_path(resource_name), :html => { :method => :post, :role => 'form'}) do |f|
      %p We'll send password reset instructions.
      = devise_error_messages!
      .form-group
        = f.label :email
        = f.email_field :email, :autofocus => true, class: 'form-control'
      = f.submit 'Reset Password', :class => 'btn btn-primary'

app/views/shared/_signin.html.haml
.signin
  .authform.formBlock
    = form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => { :role => 'form'}) do |f|
      = devise_error_messages!
      .form-group
        = f.email_field :email, :autofocus => true, class: 'form-control', placeholder: 'e-mail'
      .form-group
        = f.password_field :password, class: 'form-control', placeholder: 'password'
      - if devise_mapping.rememberable?
        .form-group
          .checkbox{:style => "width:150px"}
            %label
              = f.check_box :remember_me
              Remember me

      = f.submit 'Sign in', :class => 'btn btn-primary'

      - if devise_mapping.registerable?
        = link_to 'Sign up', new_registration_path(resource_name), class: 'btn btn-default'
      - if devise_mapping.recoverable?
        = link_to "Forgot password?", new_password_path(resource_name), class: 'btn btn-default'

app/views/shared/_signup.html.haml
.signup
  .authform.formBlock
    = form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :role => 'form'}) do |f|
      = devise_error_messages!
      .form-group
        = f.email_field :email, :autofocus => true, class: 'form-control', placeholder: 'e-mail address'
      .form-group
        = f.password_field :password, class: 'form-control', placeholder: 'password'
      .form-group
        = f.password_field :password_confirmation, class: 'form-control', placeholder: 'confirm password'
      = f.submit 'Sign up', :class => 'btn btn-primary'

app/views/shared/_teaser_header.html.haml
.teaserHeader.container
  .teaserHeader__mottoBox
    .row
      Build tomorrow.
    .row
      = link_to 'Sign up today', new_user_registration_path, class: 'btn btn-primary'
  .teaserHeader__slogan
    Together we will change the way free open source software is being developed.

app/views/shared/_testimonials.html.haml
.testimonials.container-fluid
  .row
    .testimonials__testimonial.col-md-12.col-lg-4
      .testimonials__card
        .testimonials__citation
          "When I first heard about FOSS.buzz I knew this will be definately a big thing, regardless of any further details."
        .testimonials__portrait.testimonials__portrait--first
        .testimonials__author
          Peter Guy
          %br
          %small
            — GNU Developer

    .testimonials__testimonial.hidden-md-down.col-md-12.col-lg-4
      .testimonials__card
        .testimonials__citation
          "Free software has always proven to be the way to go. FOSS.buzz is the answer to commercial free software."
        .testimonials__portrait.testimonials__portrait--second
        .testimonials__author
          Peter Guy
          %br
          %small
            — GNU Developer

    .testimonials__testimonial.hidden-md-down.col-md-12.col-lg-4
      .testimonials__card
        .testimonials__citation
          "For a long time, making money purely with open source software was extemely difficult. And that changes now radically."

        .testimonials__portrait.testimonials__portrait--third
        .testimonials__author
          Peter Guy
          %br
          %small
            — GNU Developer